# Generated by Django 4.2.4 on 2023-08-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notesesc',
            new_name='notedesc',
        ),
    ]
